language: csharp
mono: none
dotnet: 2.1.700
script:
  - dotnet build src/GlobalX.ChatBots.Core/GlobalX.ChatBots.Core.csproj
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh $NUGET_API_KEY
  on:
    branch: master
