language: csharp
mono: none
dotnet: 2.2.105
env: VERSION=1.0.0
script:
  - dotnet build src/GlobalX.ChatBots.Core/GlobalX.ChatBots.Core.csproj
deploy:
  skip_cleanup: true
  provider: script
  script:
    - dotnet pack src/GlobalX.ChatBots.Core/GlobalX.ChatBots.Core.csproj -p:PackageVersion=$VERSION -o ../../
    - dotnet nuget push GlobalX.ChatBots.Core.$VERSION.nupkg -k $NUGET_API_KEY -s nuget.org
  on:
    branch: master
